@startuml

skinparam classAttributeIconSize 0
hide empty attributes

package "Presentation" {
    class ChangePasswordUI <<presentation>> {
    }
}

package "Application" {
    class AuthzRegistry <<utility>> {
        + authenticationService() : AuthenticationService
        + authorizationService() : AuthorizationService
    }

    class AuthenticationService <<application>> {
        + changePassword(oldPwd, newPwd): boolean
    }

    class AuthorizationService <<application>> {
        + session() : Optional<UserSession>
    }
}

package "Persistence" {
    class UserRepository <<repository>> {
        + save(user): SystemUser
    }
}

package "Domain" {
    class UserSession <<domain>> {
        + authenticatedUser() : SystemUser
    }

    class SystemUser <<domain>> {
        + passwordMatches(pwd, encoder): boolean
        + changePassword(newPwd)
    }

    class Password <<domain>> {
        + encodedAndValid(pwd, policy, encoder): Optional<Password>
    }

}

' Dependencies
ChangePasswordUI ..> AuthzRegistry
ChangePasswordUI ..> AuthenticationService

AuthzRegistry --> AuthenticationService : authenticationService
AuthzRegistry --> AuthorizationService : authorizationSvc

AuthenticationService ..> AuthorizationService : authz
AuthenticationService ..> SystemUser : user
AuthenticationService ..> Password : password
AuthenticationService ..> UserRepository : rep

AuthorizationService --> UserSession : userSession

UserSession --> SystemUser

SystemUser --> Password


@enduml
