@startuml

skinparam classAttributeIconSize 0
hide empty attributes

package "Presentation" {
    class LogoutUI <<presentation>> {
    }
}

package "Application" {
    class AuthorizationService <<service>> {
        + clearSession() : Optional<UserSession>
    }

    class AuthzRegistry <<utility>> {
        + authorizationService() : AuthorizationService
    }
}

package "Domain" {
    class UserSession {
    }
}

LogoutUI ..> AuthorizationService
LogoutUI ..> AuthzRegistry
AuthzRegistry --> AuthorizationService : authorizationSvc
AuthorizationService ..> UserSession : session

@enduml
