@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - Change Password

actor "User" as USER
participant ":System" as System

autonumber

USER -> System : Request change password
activate System

System --> USER : Asks old and new password
deactivate System

USER -> System : Provide old and new password
activate System

System --> USER : Show success or failure
deactivate System

@enduml
