@startuml

skinparam classAttributeIconSize 0
hide empty attributes

    package "<<aggregate>> CafeteriaUser" {
        class CafeteriaUser <<entity>> <<root>> {
        }

        class MecanographicNumber <<value object>> <<id>> {
        }
    }

    package "<<aggregate>> SystemUser" {
        class SystemUser <<entity>> <<root>> {
        }

        class Username <<value object>> <<id>> {
        }

        class Password <<value object>> {
        }

        class Name <<value object>> {
        }

        class EmailAddress <<value object>> {
        }

        class RoleSet {
        }

        interface Set <<interface>> {
        }

        class RoleAssigment <<entity>> {
        }

        class Role <<value object>> {
        }
    }

CafeteriaUser --> MecanographicNumber
CafeteriaUser --> SystemUser : has

SystemUser --> Username
SystemUser --> Password
SystemUser --> Name
SystemUser --> EmailAddress
SystemUser --> RoleSet
RoleSet ..|> Set
Set ..> RoleAssigment
RoleAssigment --> Role

@enduml
